### ISSUE TITLE
Slowness during dev (and a thank you)

### ISSUE THREAD

**Issue by ryanditjia** [babichjacob/sapper-postcss-template#10]
First of all, thanks for making this template, I took heavy inspiration and [blogged about it](https://www.apostrof.co/blog/getting-tailwind-css-to-integrate-nicely-with-svelte-sapper).

There, I talk about the slowness that you must be experiencing too. Copy pasting here for posterity’s sake:

> // near the beginning of the post
> - Dev server takes a while to boot up (> 15s). This slowness doesn’t seem to be present in production builds.
> - Editing the global CSS file (where you initiate Tailwind) takes very long to rebuild (> 10s). Depending on your workflow, you might not have to do this often.
>
> // near the end
> I have a hunch that’s what’s causing the dev slowdown is rollup bundling the whole of Tailwind and its sourcemaps to its JS file. I’m seeing 15–30 MB of `__sapper__/dev/client/client.somehash.js` file. If we could just disable sourcemaps I think this slowdown could be halved or better.

I’ll try to look for a fix tomorrow. Thanks again.

**Comment by babichjacob** [comment]
Thank you for your interest in the project and blogging about it! I'm honored!

We've been discussing and proposing solutions to entirely disabling source maps in [issue #9](https://github.com/babichjacob/sapper-postcss-template/issues/9). I haven't looked into it _that_ deeply yet, but at the very least now we know my first idea of taking a second pass over the `main.css` file to remove them won't be a good idea because the build that happens before this will still be slow.

**Comment by wildpow** [comment]
@ryanditjia I would be interested in seeing if PR [11](https://github.com/babichjacob/sapper-postcss-template/pull/11) once merged help speed up development. Also after merge change line 21 of `rollup.config.js` from `output: config.client.output(),` to `output: { ...config.client.output(), sourcemap: false },` to not produce source maps at all.

**Comment by wildpow** [comment]
On a side note, I switched to back to `polka` from `express` just to see if it was the culprit but, no dice for me.

**Comment by babichjacob** [comment]
Just for context as to why this template switches from the default `polka` to `express` is that [the opinionated project base](https://github.com/babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template) that this template was originally based on needs `express` to be able to have `apollo-server-express` (created by TypeGraphQL).

For that reason, it's been left in here. This also probably makes it easier to get new middleware and whatnot set up in the project, since everybody makes their stuff compatible with Express.

**Comment by wildpow** [comment]
Roger that. I have more experience with Express so I kept it, I just want to see if there was a difference or not.

**Comment by babichjacob** [comment]
> Dev server takes a while to boot up (> 15s). This slowness doesn’t seem to be present in production builds.

I've also noticed that the dev server can start in 20s while a production build can finish in 13s. 

Tailwind has gotten really heavy in the past couple of versions. We can reduce those numbers to 4s for the dev server and 7s for a production build by removing the `@apply` in `index.svelte` (so that there isn't an error about referencing nonexistent classes) and setting `corePlugins: false` in `tailwind.config.js` to turn off all the default stuff. 

So... this is a solution? The solution? I'm not sure what we as a project base can do besides switching to [Tailwind's whitelist mode](https://tailwindcss.com/docs/configuration/#core-plugins). Or, perhaps we could by introducing a `minimal` or `fast` variable that defaults to `true` and is explained in the README?

**Comment by ryanditjia** [comment]
The second method (using `rollup-plugin-postcss`) that I mentioned in my blog post doesn’t have this slowness issue, because rollup doesn’t write the CSS and its sourcemaps to JS. In that method, we import Tailwind inside `src/server.js` and it spits out a CSS that we link to from `template.html`.

See my boilerplate up to this commit: https://github.com/ryanditjia/sapper-boilerplate/tree/37590a31b50768a8ced09b209d428e7ccd07a049

I had 3 issues with that:

- Double reloads every edit. This could sometimes result in no server found error (when preload is slow, e.g. external data), requiring manual reload.
- Inability to inline critical Tailwind classes
- I needed to revert to rollup-plugin-postcss 2.8.x because 3.x still has [an issue](https://github.com/egoist/rollup-plugin-postcss/issues/250)

Hence my move to this method. It doesn’t scale well the larger your Tailwind config gets. In dev, the JS files are too darn big. See: `__sapper__/dev/client/client.somehash.js` (only when emitCss is false), and `__sapper__/dev/server/server.js` for what’s causing the slow dev.

This isn’t a problem for me, but I’ve been talking to someone whose config is so extensive its dev takes 5 mins to boot up.

I tried #11 but it doesn’t seem to have much effect, and I’m not versed too well in sourcemaps to know the negative effects disabling it might cause.

I’m afraid I don’t have a solution for this 😅. Feel free to close this issue if you aren’t bothered by it.

**Comment by wildpow** [comment]
@ryanditjia Thank you for your input. I'll take a look at your repo and combine the approaches somehow. I believe there is a solution to all our issues we just haven't found it yet.

**Comment by autoferrit** [comment]
Do we have a current fix for this? Turning off sourcemaps entirely still has a startup of 37 seconds for me.

**Comment by babichjacob** [comment]
In reaction to https://github.com/babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template/issues/18, I might make changes (in this template too) that will also cut down dev time by making all of the global CSS be processed in parallel instead of blocking the Svelte compiler.

**Comment by babichjacob** [comment]
That's also what the [official setup example](https://github.com/tailwindlabs/tailwindcss-setup-examples/tree/master/examples/sapper) (which does not use `svelte-preprocess` at all, even though it would still be fast and possible) does.

**Comment by autoferrit** [comment]
reading that issue, you would convert the files to use common.js and use the experimental tailwind features?

**Comment by babichjacob** [comment]
Can you/anyone try the [`parallel-global-css`](https://github.com/babichjacob/sapper-postcss-template/tree/parallel-global-css) branch and provide feedback? For me, the initial `dev` build went from 40 seconds to 10 seconds (with the CSS-less build available in just 2 seconds).

**Comment by yorgyetson** [comment]
I'm getting an error trying the parallel-global-css branch

`npm run dev

> sapper-postcss-template@2020.8.27 dev C:\development\sapper-postcss-template
> sapper dev

(node:10148) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from C:\development\sapper-postcss-template\build-global-css.mjs
    at packageResolve (internal/modules/esm/resolve.js:594:9)
    at moduleResolve (internal/modules/esm/resolve.js:633:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
global css builder exited with code 1
✗ global css
✔ client (2.5s)
(node:24392) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from C:\development\sapper-postcss-template\build-global-css.mjs
    at packageResolve (internal/modules/esm/resolve.js:594:9)
    at moduleResolve (internal/modules/esm/resolve.js:633:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
global css builder exited with code 1
✗ global css
✔ server (2.9s)
✔ service worker (95ms)
> Listening on http://localhost:3000`

It starts fast though.

**Comment by babichjacob** [comment]
Thanks for the info. I was worried about Windows compatibility. What version of Node are you on?

**Comment by yorgyetson** [comment]
node -v
v12.18.3

**Comment by babichjacob** [comment]
Does (the latest minor version of) Node 14 work? (At the very least, it'll remove warnings about the experimental ESM loader).

**Comment by yorgyetson** [comment]
Yes, that fixed it.

node -v
v14.9.0

npm run dev

> sapper-postcss-template@2020.8.27 dev C:\development\sapper-postcss-template
> sapper dev

✔ client (3.0s)
✔ server (3.5s)
✔ service worker (83ms)
> Listening on http://localhost:3000
✔ global css (src/global.pcss → static/global.css) (9804ms)

**Comment by babichjacob** [comment]
I added Node 12 compatibility in the latest commit https://github.com/babichjacob/sapper-postcss-template/commit/3251960d8de1ed4b0575c735b8be55158c5f20cf

**Comment by yorgyetson** [comment]
Confirming that it's working on Node 12 on Windows 10.

(base) PS C:\development\sapper-postcss-template> git branch  
  main


> * parallel-global-css

(base) PS C:\development\sapper-postcss-template> node -v
v12.18.3
(base) PS C:\development\sapper-postcss-template> npm run dev

> sapper-postcss-template@2020.8.27 dev C:\development\sapper-postcss-template
> sapper dev

(node:26580) ExperimentalWarning: The ESM module loader is experimental.
✔ client (2.0s)
✔ server (2.3s)
✔ service worker (44ms)
> Listening on http://localhost:3000
✔ global css (src/global.pcss → static/global.css) (7232ms)

**Comment by mcmxcdev** [comment]
For my project, the `sapper dev` command takes 24s instead of 54s with the `parallel-global-css` branch!
Great job there ;)

I just see the log message for `global css (src/global.pcss → static/global.css)` appearing double in dev and a lot of times when using `sapper build`, not sure if this is correct or not.

**Comment by babichjacob** [comment]
> I just see the log message for `global css (src/global.pcss → static/global.css)` appearing double in dev and a lot of times when using `sapper build`, not sure if this is correct or not.

@mhatvan I see it exactly twice from the `prod` script in an unmodified clone
