### ISSUE TITLE
Upgrade postcss-focus-within and remove workaround

### ISSUE THREAD

**Issue by benmccann** [babichjacob/sapper-postcss-template#16]
I noticed this comment:

https://github.com/babichjacob/sapper-postcss-template/blob/1f98f4f07bc65bd7b627aaaba3b282e579267510/postcss.config.js#L19

The `package-lock` sets `postcss-focus-within` to `3.0.0`. It looks like that issue was fixed https://github.com/csstools/postcss-focus-within/issues/3 and released as 4.0.0

I'd send you a PR, but haven't actually used postcss at all, so wouldn't be quite sure how to test. I was hoping to use this template to help debug an issue someone reported in Sapper and just happened to notice that while taking a look

**Comment by babichjacob** [comment]
I can't manage to force use of `postcss-focus-within@4.0.0` without it being reverted on the next `install`, so we'll have to wait for `postcss-preset-env` to update its dependencies

**Comment by benmccann** [comment]
It looks like there's a PR for it here: https://github.com/csstools/postcss-preset-env/pull/172

**Comment by benmccann** [comment]
But maybe they're waiting to upgrade it until the larger set of upgrades in https://github.com/csstools/postcss-preset-env/pull/174 which is also bumping it

**Comment by babichjacob** [comment]
`postcss-preset-env` has been removed from the template instead because it's semi-unmaintained and comments explaining where to add it / similar polyfills (like the ones it delegates work to) were added in its place.

b5ceec6a5d1aaf273424c57cb5e189fe87905351
