### ISSUE TITLE
Dev build works, build or export fails with message

### ISSUE THREAD

**Issue by SumitBando** [babichjacob/sapper-postcss-template#19]
Unmodified cloned repo.
npm run build or npm build export
fails with
[!] (plugin svelte) TypeError: content.matchAll(...) is not a function or its return value is not iterable
TypeError: content.matchAll(...) is not a function or its return value is not iterable
    at defaultExtractor (sapper-postcss-template/postcss.config.js:26:47)
    at m (purgecss.js:1:3149)
    at x.extractSelectorsFromFiles (purgecss/lib/purgecss.js:1:5183)

**Comment by babichjacob** [comment]
I think you're on a version of Node lower than 12 (without the `matchAll` method on strings)?

**Comment by SumitBando** [comment]
Correct, closing.
