### ISSUE TITLE
error  'preprocess' is assigned a value but never used  no-unused-vars

### ISSUE THREAD

**Issue by sakurasato** [babichjacob/sapper-postcss-template#21]
Hi Jacob! I noticed when I run yarn lint:fix on new repository it shows the error in `sapper-postcss-template/rollup.config.js`

`error  'preprocess' is assigned a value but never used  no-unused-vars`

I'm not to familiar with Rollup and just getting started with Svelte, is this something that's safe to ignore?

Thank you!

**Comment by babichjacob** [comment]
I'm surprised this is even happening? `preprocess` is *for sure* being used

**Comment by sakurasato** [comment]
I see what I did wrong, I added svex to your rollupconfig so using

```
svelte({
  dev,
  hydratable: true,
  emitCss: true,
  preprocess,
  extensions: [
    ".svelte",
    ".svx",
  ],
  preprocess: mdsvex(),
}),
```
Made eslint not recognize the preprocess for some reason. Sorry Jacob!

**Comment by babichjacob** [comment]
It's best to add mdsvex in [`svelte.config.js` at the mark](https://github.com/babichjacob/sapper-postcss-template/blob/main/svelte.config.js#L12)
