### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dikaio** [babichjacob/sapper-postcss-template#23]
Hi @babichjacob. I noticed you've added tailwind 2.0 into your theme, I was going to take it for a spin but ran into a "Cannot read property ''length of undefined". Is there any it's doing the same for you?

```
Cannot read property 'length' of undefined
✔ global css (src/global.pcss → static/global.css) (3339ms)
node:internal/modules/cjs/loader:922
  throw err;
  ^

Error: Cannot find module '/Users/dad/Desktop/sapper-postcss-template/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by babichjacob** [comment]
I can reproduce. This looks like a problem with all Sapper projects right now.

For now, downgrade the `"svelte"` version to `"3.29.7"` and keep `"rollup-plugin-svelte"` *not* on version 7.

**Comment by babichjacob** [comment]
Linked issues / PRs:

https://github.com/sveltejs/svelte/issues/5722
https://github.com/sveltejs/rollup-plugin-svelte/issues/160
https://github.com/sveltejs/rollup-plugin-svelte/pull/145

**Comment by dikaio** [comment]
Works, thank you @babichjacob. Will take a peak into the related issues now.

**Comment by babichjacob** [comment]
This has since been fixed upstream *and* this project base has been updated yesterday. 👍
