### ISSUE TITLE
Mdsvex?

### ISSUE THREAD

**Issue by nemo-omen** [babichjacob/sapper-postcss-template#25]
So, I've been chasing my tail for a few hours trying to figure out how to get mdsvex working with this template (which is a fantastic template, by the way!)

Do you have any suggestions of where/how one would go about integrating it here?

Thanks in advance!

**Comment by nemo-omen** [comment]
Well, son of a gun, I got it working! Turns out I needed to use `const {mdsvex} = require('mdsvex')` instead of `const mdsvex = require('mdsvex')`.

**Comment by babichjacob** [comment]
Great!

**Comment by nemo-omen** [comment]
I should add that this only works if I declare `mdsvex()` above `sveltePreprocess()` in `svelte.config.js`.
