### ISSUE TITLE
Disable CSS source maps

### ISSUE THREAD

**Issue by wildpow** [babichjacob/sapper-postcss-template#9]
In development, a separate CSS source map is created for `main.css` and also the source map is turned into base64 and inlined in `main.css`. In turn build and export get both copies as well. 
Producing a 9.6meg `main.css.map` file and a 315kb `main.css` in my very basic 6-page project.

I've tried a few things already. Via Sapper PR [768](https://github.com/sveltejs/sapper/pull/768)
I changed the client output to `output: { ...config.client.output(), sourcemap: dev },` and server to `output: { ...config.server.output(), sourcemap: dev },` in `rollup.conf.js` Which did not have an effect. 

I was able to stop the separate source map from being created by passing a second argument into `css.wrtite` in `rollup.config.js` but a copy still gets inlined. 

PR [8](https://github.com/babichjacob/sapper-postcss-template/pull/8) to remove the separate source map.

**Comment by babichjacob** [comment]
Hmm. It would definitely be outside the range of what I'm familiar with but it _may_ be possible to take a second pass over the `main.css` file in the preprocessor to remove all (source map only if possible) comments. Perhaps an additional (environment) variable can be used to control this behavior instead of tying it to `dev`.

I might investigate this in ~18 or more hours.

**Comment by wildpow** [comment]
If I had to guess it's PostCSS doing the inlining and there is a setting, we could add to the config to stop this from happening in production. Let me know what you come up with, I'll keep looking too.

**Comment by wildpow** [comment]
The problem with the separate source map was it was written once in development, and then Sapper just treated it as a static asset and carried it over. The production CSS gets messed with by purge and nano. Wonder if they could take care of it 🤔

**Comment by wildpow** [comment]
PR [11](https://github.com/babichjacob/sapper-postcss-template/pull/11) fixes this
